### ISSUE TITLE
Need simple example showing how to apply dcb settings from the application

### ISSUE THREAD

**Issue by jerrywrice** [de-vri-es/serial2-rs#16]
I'm a relative novice using type conversion operators (such Into) with rust. 

Could you add an example source file that applies port settings using the DCB under Windows? To be clear, I understand how the serial DCB fields work with Windows serial ports, but don't know how to accomplish this from a rust application using the serial2 crate.

Thx

**Comment by de-vri-es** [comment]
Is there anything from [`Settings`](https://docs.rs/serial2/latest/serial2/struct.Settings.html) yuo're missing? Do you want access to the raw `DCB` structure?

**Comment by jerrywrice** [comment]
Maarten,

 

Thanks for replying, and for publishing and supporting this create.
 
In my application I need to customize the Windows Receive timeout configuration, based on the device I’m controlling. I need to set a variety of combinations of the DCB ReadIntervalTimeout, ReadTotalTimeoutMultiplier, and ReadTotalTimeoutConstant DCB fields, depending upon the specific application requirements.
 
I haven’t found a way to do this without modifying the crate interface. 
 
Is there a way to update the raw DCB from outside the crate library - from a client application?
 
Best,

 

Jerry  W. Rice, Chief Technology Officer

 <http://www.FABNexus.com> www.FABNexus.com

660 Arboleda Drive

Los Altos, CA 94024

Email:  ***@***.***> ***@***.***

Cell:    650-207-8235

**Comment by de-vri-es** [comment]
Hey! Currently there is indeed no way to access the raw `DCB` fields or the timeouts. Do note that the timeouts are not in the `DCB` struct, they're in the `_COMMTIMEOUTS` struct, which requires a separate set of syscalls to manipulate.

I am interested in exposing platform specific configuration parameters, but there are some challenges with that. Would it suffice for your application to just set the read/write timeout (`ReadTotalTimeoutConstant`)? Because that is already exposed through [`set_read_timeout()`](https://docs.rs/serial2/latest/serial2/struct.SerialPort.html#method.set_read_timeout).

Note that setting `ReadIntervalTimeout` and `ReadTotalTimeoutMultiplier` will cause `read()` to return no data if the timeout is reached, not even whatever data has been received so far. This is normally a big problem, so you should be careful when using these settings.

**Comment by jerrywrice** [comment]
Maarten,

 

Yes, I understand those Windows data structures. I was a bit rushed with I formulated my earlier email. Note that I recently collaborated and volunteered time/effort to supplying updates to those setting fields for the ‘serialport-rs’ crate.

 

Unfortunately that crate’s support team is very preoccupied with other things besides that crate – something I’m sure you must content with as well (we’re all volunteers!). But after almost six months of roughly 20 hours per week assisting that crate’s support team I concluded things were moving too slow. Recently someone referred me to your crate, which is why I began experimenting with it about a week or so back.

 

Let me know if you have a need/interest in adding to your open source volunteer support team – I have some time as I’m semi-retired. Regarding my background, I’ve been using rust for some in-house projects for about a year now. IMO it’s a great system’s development language, one of the best I’ve encountered in my career. You can check out my technical resume on my web-site (URL below).

 

Cheers,

 

Jerry  W. Rice, Chief Technology Officer

 <http://www.FABNexus.com> www.FABNexus.com

660 Arboleda Drive

Los Altos, CA 94024

Email:  ***@***.***> ***@***.***

Cell:    650-207-8235

**Comment by de-vri-es** [comment]
Hey! As mentioned, I do want to support access to platform specific features.

It's currently open in #18.

**Comment by jerrywrice** [comment]
Your latest merge of pr #18 into main resolves my request. Thx.
